# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/.Xil/Vivado-17344-ENGR-6W5DS33/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.cache/wt [current_project]
set_property parent.project_path C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths c:/Users/r673h066/repo [current_project]
update_ip_catalog
set_property ip_output_repo c:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/imports/hdl/AudioDemo.vhd
  C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/imports/hdl/Dbncr.vhd
  C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/imports/hdl/PdmDes.vhd
  C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/imports/hdl/PdmSer.vhd
  C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/imports/hdl/Ram2Ddr.vhd
  C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/imports/hdl/RamCntrl.vhd
  C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/imports/hdl/top.vhd
}
read_ip -quiet C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/ip/ddr/ddr.xci
set_property used_in_implementation false [get_files -all c:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr.xdc]
set_property used_in_implementation false [get_files -all c:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/ip/ddr/ddr/user_design/constraints/ddr_ooc.xdc]

read_ip -quiet C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/ip/ClkGen/ClkGen.xci
set_property used_in_implementation false [get_files -all c:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/ip/ClkGen/ClkGen_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/ip/ClkGen/ClkGen.xdc]
set_property used_in_implementation false [get_files -all c:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/sources_1/ip/ClkGen/ClkGen_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/r673h066/Downloads/final_project_443/final_project_443/vivado_proj/final_project.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
